name: RDP with Python Tool
on:
  workflow_dispatch:

jobs:
  rdp-job:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:

      # 1) جلب ملفات الريبو
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) تفعيل RDP وفتح المنفذ 3389
      - name: Enable RDP
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP-Allow-3389" dir=in action=allow protocol=TCP localport=3389

      # 3) إنشاء مستخدم TOOLBOXLAP بكلمة سر ثابتة
      - name: Create RDP user TOOLBOXLAP
        shell: pwsh
        run: |
          $password = "admin@123"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (-not (Get-LocalUser -Name "TOOLBOXLAP" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "TOOLBOXLAP" -Password $securePass -AccountNeverExpires -PasswordNeverExpires
          }
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "TOOLBOXLAP"
          Write-Host "RDP user TOOLBOXLAP تم إنشاؤه"

      # 4) نسخ ملفات script.py و users.txt إلى سطح المكتب داخل RDP
      - name: Copy Python tool and users.txt to RDP
        shell: pwsh
        run: |
          # إذا الملفات في جذر الريبو مباشرة
          $src = $env:GITHUB_WORKSPACE
          # إذا الملفات في مجلد داخلي بنفس اسم الريبو، استخدم:
          # $src = Join-Path $env:GITHUB_WORKSPACE 'rdp-files'
          $dest = 'C:\Users\TOOLBOXLAP\Desktop\rdp-files'
          New-Item -Path $dest -ItemType Directory -Force | Out-Null
          Copy-Item -Path "$src\script.py" -Destination $dest -Force
          Copy-Item -Path "$src\users.txt" -Destination $dest -Force
          Write-Host "Files copied to $dest"

      # 5) إظهار معلومات RDP للاتصال
      - name: Show RDP info
        shell: pwsh
        run: |
          Write-Host "==== RDP ACCESS ===="
          Write-Host "Username: TOOLBOXLAP"
          Write-Host "Password: admin@123"
          Write-Host "Connect using RDP to this runner's IP"
          while ($true) { Start-Sleep -Seconds 300 }
